version: 0.0.{build}
branches:
  only:
  - master
os: Visual Studio 2015
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: nuget restore src/Wix.AssemblyInfo.sln
build:
  project: src/Wix.AssemblyInfo.sln
  verbosity: minimal