version: 0.0.{build}
branches:
  only:
  - master
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: nuget restore src/Wix.AssemblyInfo.sln
build:
  project: src/Wix.AssemblyInfo/Wix.AssemblyInfo.csproj
  verbosity: minimal